// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.0.0.30. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ConfigMaker.Model
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class settings : System.ComponentModel.INotifyPropertyChanged
{
    
    private string _filename;
    
    private string _mode;
    
    private BindingList<settingsPostprocess> _postprocess;
    
    private string _useragent;
    
    private BindingList<settingsDecryptkey> _decryptkey;
    
    private settingsLicense _license;
    
    private string _logging;
    
    private settingsRetry _retry;
    
    private settingsProxy _proxy;
    
    private string _timespan;
    
    private string _update;
    
    private string _skip;
    
    private BindingList<siteChannel> _channel;
    
    private static XmlSerializer serializer;
    
    public settings()
    {
        this._channel = new BindingList<siteChannel>();
        this._proxy = new settingsProxy();
        this._retry = new settingsRetry();
        this._license = new settingsLicense();
        this._decryptkey = new BindingList<settingsDecryptkey>();
        this._postprocess = new BindingList<settingsPostprocess>();
    }
    
    public string filename
    {
        get
        {
            return this._filename;
        }
        set
        {
            if ((this._filename == value))
            {
                return;
            }
            if (((this._filename == null) 
                        || (_filename.Equals(value) != true)))
            {
                this._filename = value;
                this.OnPropertyChanged("filename");
            }
        }
    }
    
    public string mode
    {
        get
        {
            return this._mode;
        }
        set
        {
            if ((this._mode == value))
            {
                return;
            }
            if (((this._mode == null) 
                        || (_mode.Equals(value) != true)))
            {
                this._mode = value;
                this.OnPropertyChanged("mode");
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("postprocess")]
    public BindingList<settingsPostprocess> postprocess
    {
        get
        {
            return this._postprocess;
        }
        set
        {
            if ((this._postprocess == value))
            {
                return;
            }
            if (((this._postprocess == null) 
                        || (_postprocess.Equals(value) != true)))
            {
                this._postprocess = value;
                this.OnPropertyChanged("postprocess");
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("user-agent")]
    public string useragent
    {
        get
        {
            return this._useragent;
        }
        set
        {
            if ((this._useragent == value))
            {
                return;
            }
            if (((this._useragent == null) 
                        || (_useragent.Equals(value) != true)))
            {
                this._useragent = value;
                this.OnPropertyChanged("useragent");
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("decryptkey")]
    public BindingList<settingsDecryptkey> decryptkey
    {
        get
        {
            return this._decryptkey;
        }
        set
        {
            if ((this._decryptkey == value))
            {
                return;
            }
            if (((this._decryptkey == null) 
                        || (_decryptkey.Equals(value) != true)))
            {
                this._decryptkey = value;
                this.OnPropertyChanged("decryptkey");
            }
        }
    }
    
    public settingsLicense license
    {
        get
        {
            return this._license;
        }
        set
        {
            if ((this._license == value))
            {
                return;
            }
            if (((this._license == null) 
                        || (_license.Equals(value) != true)))
            {
                this._license = value;
                this.OnPropertyChanged("license");
            }
        }
    }
    
    public string logging
    {
        get
        {
            return this._logging;
        }
        set
        {
            if ((this._logging == value))
            {
                return;
            }
            if (((this._logging == null) 
                        || (_logging.Equals(value) != true)))
            {
                this._logging = value;
                this.OnPropertyChanged("logging");
            }
        }
    }
    
    public settingsRetry retry
    {
        get
        {
            return this._retry;
        }
        set
        {
            if ((this._retry == value))
            {
                return;
            }
            if (((this._retry == null) 
                        || (_retry.Equals(value) != true)))
            {
                this._retry = value;
                this.OnPropertyChanged("retry");
            }
        }
    }
    
    public settingsProxy proxy
    {
        get
        {
            return this._proxy;
        }
        set
        {
            if ((this._proxy == value))
            {
                return;
            }
            if (((this._proxy == null) 
                        || (_proxy.Equals(value) != true)))
            {
                this._proxy = value;
                this.OnPropertyChanged("proxy");
            }
        }
    }
    
    public string timespan
    {
        get
        {
            return this._timespan;
        }
        set
        {
            if ((this._timespan == value))
            {
                return;
            }
            if (((this._timespan == null) 
                        || (_timespan.Equals(value) != true)))
            {
                this._timespan = value;
                this.OnPropertyChanged("timespan");
            }
        }
    }
    
    public string update
    {
        get
        {
            return this._update;
        }
        set
        {
            if ((this._update == value))
            {
                return;
            }
            if (((this._update == null) 
                        || (_update.Equals(value) != true)))
            {
                this._update = value;
                this.OnPropertyChanged("update");
            }
        }
    }
    
    public string skip
    {
        get
        {
            return this._skip;
        }
        set
        {
            if ((this._skip == value))
            {
                return;
            }
            if (((this._skip == null) 
                        || (_skip.Equals(value) != true)))
            {
                this._skip = value;
                this.OnPropertyChanged("skip");
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("channel")]
    public BindingList<siteChannel> channel
    {
        get
        {
            return this._channel;
        }
        set
        {
            if ((this._channel == value))
            {
                return;
            }
            if (((this._channel == null) 
                        || (_channel.Equals(value) != true)))
            {
                this._channel = value;
                this.OnPropertyChanged("channel");
            }
        }
    }
    
    private static XmlSerializer Serializer
    {
        get
        {
            if ((serializer == null))
            {
                serializer = new XmlSerializerFactory().CreateSerializer(typeof(settings));
            }
            return serializer;
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    public virtual void OnPropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
        if ((handler != null))
        {
            handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current settings object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public virtual string Serialize(System.Text.Encoding encoding)
    {
        System.IO.StreamReader streamReader = null;
        System.IO.MemoryStream memoryStream = null;
        try
        {
            memoryStream = new System.IO.MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Encoding = encoding;
            xmlWriterSettings.Indent = true;
            xmlWriterSettings.IndentChars = "  ";
            xmlWriterSettings.OmitXmlDeclaration = true;
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, SeekOrigin.Begin);
            streamReader = new System.IO.StreamReader(memoryStream, encoding);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }
    
    public virtual string Serialize()
    {
        return Serialize(System.Text.Encoding.UTF8);
    }
    
    /// <summary>
    /// Deserializes workflow markup into an settings object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output settings object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out settings obj, out System.Exception exception)
    {
        exception = null;
        obj = default(settings);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (System.Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out settings obj)
    {
        System.Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public new static settings Deserialize(string input)
    {
        System.IO.StringReader stringReader = null;
        try
        {
            stringReader = new System.IO.StringReader(input);
            return ((settings)(Serializer.Deserialize(XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }
    
    public static settings Deserialize(System.IO.Stream s)
    {
        return ((settings)(Serializer.Deserialize(s)));
    }
    #endregion
    
    /// <summary>
    /// Serializes current settings object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName, encoding);
            return true;
        }
        catch (System.Exception e)
        {
            exception = e;
            return false;
        }
    }
    
    public virtual bool SaveToFile(string fileName, out System.Exception exception)
    {
        return SaveToFile(fileName, System.Text.Encoding.UTF8, out exception);
    }
    
    public virtual void SaveToFile(string fileName)
    {
        SaveToFile(fileName, System.Text.Encoding.UTF8);
    }
    
    public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
    {
        System.IO.StreamWriter streamWriter = null;
        try
        {
            string xmlString = Serialize(encoding);
            streamWriter = new System.IO.StreamWriter(fileName, false, encoding);
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes xml markup from file into an settings object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output settings object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out settings obj, out System.Exception exception)
    {
        exception = null;
        obj = default(settings);
        try
        {
            obj = LoadFromFile(fileName, encoding);
            return true;
        }
        catch (System.Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool LoadFromFile(string fileName, out settings obj, out System.Exception exception)
    {
        return LoadFromFile(fileName, System.Text.Encoding.UTF8, out obj, out exception);
    }
    
    public static bool LoadFromFile(string fileName, out settings obj)
    {
        System.Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }
    
    public static settings LoadFromFile(string fileName)
    {
        return LoadFromFile(fileName, System.Text.Encoding.UTF8);
    }
    
    public new static settings LoadFromFile(string fileName, System.Text.Encoding encoding)
    {
        System.IO.FileStream file = null;
        System.IO.StreamReader sr = null;
        try
        {
            file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new System.IO.StreamReader(file, encoding);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
    
    #region Clone method
    /// <summary>
    /// Create a clone of this settings object
    /// </summary>
    public virtual settings Clone()
    {
        return ((settings)(this.MemberwiseClone()));
    }
    #endregion
}
}
#pragma warning restore
