//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] log4netconfig {
            get {
                object obj = ResourceManager.GetObject("log4netconfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;settings&gt;
        ///   
        ///  &lt;!-- for detailed info about the settings see http://webgrabplus.com/documentation/configuration/webgrabconfigxml 
        ///  and http://webgrabplus.com/sites/default/files/downloads/Misc/Documented_Configuration_Files.zip --&gt;
        ///   
        ///  &lt;filename&gt;guide.xml&lt;/filename&gt;
        ///  &lt;mode&gt;f&lt;/mode&gt;
        ///  &lt;postprocess grab=&quot;y&quot; run=&quot;n&quot;&gt;rex&lt;/postprocess&gt;
        ///  &lt;postprocess grab=&quot;y&quot; run=&quot;n&quot;&gt;mdb&lt;/postprocess&gt;
        ///  &lt;user-agent&gt;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebGrab_config_example {
            get {
                return ResourceManager.GetString("WebGrab_config_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;settings&gt;
        ///
        ///  &lt;!-- for detailed info about the settings see http://webgrabplus.com/documentation/configuration/webgrabconfigxml 
        ///  and http://webgrabplus.com/sites/default/files/downloads/Misc/Documented_Configuration_Files.zip --&gt;
        ///
        ///  &lt;filename&gt;guide.xml&lt;/filename&gt;
        ///  &lt;mode&gt;&lt;/mode&gt;
        ///  &lt;postprocess grab=&quot;y&quot; run=&quot;n&quot;&gt;rex&lt;/postprocess&gt;
        ///  &lt;user-agent&gt;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71&lt;/us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebGrab_config_template {
            get {
                return ResourceManager.GetString("WebGrab_config_template", resourceCulture);
            }
        }
    }
}
